/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    categories: Category;
    demandes: Demande;
    abonnes: Abonne;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    demandes: DemandesSelect<false> | DemandesSelect<true>;
    abonnes: AbonnesSelect<false> | AbonnesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en') | ('fr' | 'en')[];
  globals: {
    accueil: Accueil;
    blog: Blog;
    contact: Contact;
    navigation: Navigation;
  };
  globalsSelect: {
    accueil: AccueilSelect<false> | AccueilSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: 'fr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Décrit l’image pour les lecteurs d’écran et le SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  titre: string;
  /**
   * Sans barre oblique : « competences », « expertise ».
   */
  slug: string;
  /**
   * Détermine l’URL et le fil d’ariane. Laisser vide pour une page de premier niveau.
   */
  parent?: (number | null) | Page;
  /**
   * Bascule la page sur le hero sur photo et y affiche le logotype du pôle. Laisser vide pour une page ordinaire.
   */
  pole?: ('expertise' | 'capital' | 'feed') | null;
  /**
   * Deux ou trois mots situant le pôle (« Pôle cœur »). Affichée sur la bande des pôles de l’accueil.
   */
  accrocheCourte?: string | null;
  surtitre?: string | null;
  /**
   * Le grand titre du hero, distinct du titre de la page.
   */
  accroche?: string | null;
  description?: string | null;
  image?: (number | null) | Media;
  cta?: {
    libelle?: string | null;
    /**
     * Sans préfixe de langue.
     */
    chemin?: string | null;
  };
  sections?:
    | (
        | {
            /**
             * À laisser décoché quand le hero de la page annonce déjà les pôles. Le titre reste alors saisi : il n’est plus affiché, mais les lecteurs d’écran l’annoncent avant les trois bandes.
             */
            avecEnTete?: boolean | null;
            surtitre?: string | null;
            titreHaut?: string | null;
            titreBas?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bandePoles';
          }
        | {
            surtitre?: string | null;
            titre: string;
            texte: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'synergie';
          }
        | {
            surtitre: string;
            titre: string;
            /**
             * Affichée à droite du titre.
             */
            chapo?: string | null;
            intitules?:
              | {
                  texte: string;
                  /**
                   * Facultative. Affichée sous l’intitulé, précédée d’une flèche.
                   */
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'grille';
          }
        | {
            surtitre: string;
            titre: string;
            chapo: string;
            /**
             * Chaque carte porte soit un numéro, soit un pictogramme. La dernière est souvent mise en avant.
             */
            cartes?:
              | {
                  numero?: string | null;
                  /**
                   * Remplace le numéro s’il est renseigné.
                   */
                  picto?: ('antenne' | 'stockage' | 'systemes') | null;
                  titre: string;
                  texte: string;
                  accentuee?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'escalier';
          }
        | {
            surtitre: string;
            /**
             * Facultatif. Affiché en retrait devant le titre.
             */
            titreHaut?: string | null;
            titreBas: string;
            /**
             * Les fonds s’assombrissent dans l’ordre : la progression suit la position.
             */
            cartes?:
              | {
                  picto: 'antenne' | 'securite' | 'balance' | 'boussole' | 'dette' | 'alerte' | 'liens';
                  titre: string;
                  description: string;
                  reponse: string;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'enjeux';
          }
        | {
            surtitre: string;
            titre: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'promesse';
          }
        | {
            surtitre: string;
            titre: string;
            /**
             * Première moitié du chapô, à pleine intensité.
             */
            constat: string;
            /**
             * Facultative. Affichée en retrait à la suite du constat — l’accueil l’emploie, Capital énonce d’un seul tenant.
             */
            consequence?: string | null;
            statistiques?:
              | {
                  valeur: string;
                  unite: string;
                  libelle: string;
                  precision: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'chiffres';
          }
        | {
            surtitre: string;
            titre: string;
            libelleAction: string;
            /**
             * Les derniers articles publiés sont repris automatiquement : leur contenu se gère depuis le blog.
             */
            nombre: number;
            id?: string | null;
            blockName?: string | null;
            blockType: 'articles';
          }
        | {
            surtitre: string;
            titre: string;
            image?: (number | null) | Media;
            questions?:
              | {
                  question: string;
                  /**
                   * Sans réponse, la question s’affiche sans pouvoir se déplier.
                   */
                  reponse?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            surtitre: string;
            titre: string;
            habituelle: {
              badge: string;
              titre: string;
              /**
               * Alternative aux puces : la page Media énonce d’un bloc là où l’accueil détaille point par point.
               */
              texte?: string | null;
              puces?:
                | {
                    texte: string;
                    id?: string | null;
                  }[]
                | null;
            };
            bone: {
              badge: string;
              titre: string;
              /**
               * Alternative aux puces : la page Media énonce d’un bloc là où l’accueil détaille point par point.
               */
              texte?: string | null;
              puces?:
                | {
                    texte: string;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'differenciation';
          }
        | {
            surtitre: string;
            /**
             * Les fichiers vivent dans public/brand/partenaires. Ajouter un partenaire suppose d’y déposer son SVG.
             */
            logos?:
              | {
                  fichier: string;
                  nom: string;
                  /**
                   * Calée à l’œil dans la maquette : les logos n’ont pas le même poids optique.
                   */
                  hauteur: number;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'partenaires';
          }
        | {
            surtitre: string;
            refus: {
              intitule: string;
              citation: string;
              precision?: string | null;
            };
            engagement: {
              intitule: string;
              citation: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'posture';
          }
        | {
            surtitre: string;
            titre: string;
            enTetes: {
              profil: string;
              pointEntree: string;
              livrable: string;
            };
            lignes?:
              | {
                  profil: string;
                  pointEntree: string;
                  livrable: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pointsEntree';
          }
        | {
            surtitre: string;
            titre: string;
            chapo: string;
            libelleChamp: string;
            libelleBouton: string;
            messageSucces: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
        | {
            surtitre?: string | null;
            corps: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'texteLong';
          }
        | {
            cartes?:
              | {
                  prefixe?: string | null;
                  valeur: string;
                  suffixe?: string | null;
                  libelle: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'reperes';
          }
        | {
            surtitre: string;
            cartes?:
              | {
                  picto: 'diplome' | 'eclair' | 'boucle' | 'cible' | 'bouclier' | 'direction' | 'ampoule' | 'personne';
                  titre: string;
                  texte: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'valeurs';
          }
        | {
            surtitre: string;
            titre: string;
            chapo: string;
            traits?:
              | {
                  picto: 'diplome' | 'eclair' | 'boucle' | 'cible' | 'bouclier' | 'direction' | 'ampoule' | 'personne';
                  libelle: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'archetype';
          }
        | {
            surtitre: string;
            titre: string;
            texte: string;
            image?: (number | null) | Media;
            statistiques?:
              | {
                  valeur: string;
                  libelle: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'equipe';
          }
        | {
            surtitre: string;
            titre: string;
            chapo: string;
            cta: {
              libelle: string;
              chemin: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'appelAction';
          }
      )[]
    | null;
  /**
   * À défaut, le titre de la page est utilisé.
   */
  metaTitre?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  titre: string;
  /**
   * Sans barre oblique.
   */
  slug: string;
  categorie: number | Category;
  publieLe: string;
  minutesLecture: number;
  /**
   * Affiché sur la carte, sous le titre.
   */
  extrait: string;
  image?: (number | null) | Media;
  contenu?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ce qui suit le corps de l’article : les articles à lire aussi, la FAQ et l’appel à l’action.
   */
  sections?:
    | (
        | {
            surtitre: string;
            titre: string;
            libelleAction: string;
            /**
             * Les derniers articles publiés sont repris automatiquement : leur contenu se gère depuis le blog.
             */
            nombre: number;
            id?: string | null;
            blockName?: string | null;
            blockType: 'articles';
          }
        | {
            surtitre: string;
            titre: string;
            image?: (number | null) | Media;
            questions?:
              | {
                  question: string;
                  /**
                   * Sans réponse, la question s’affiche sans pouvoir se déplier.
                   */
                  reponse?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            surtitre: string;
            titre: string;
            chapo: string;
            cta: {
              libelle: string;
              chemin: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'appelAction';
          }
      )[]
    | null;
  metaTitre?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  _order?: string | null;
  nom: string;
  /**
   * Version développée du nom, pour les filtres du blog : « Capital » sur l’étiquette d’une carte, « Revalorisation / Capital » dans la barre. Vide, le nom sert aux deux.
   */
  libelleLong?: string | null;
  /**
   * Sert au filtrage du blog. Non localisé.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demandes".
 */
export interface Demande {
  id: number;
  profil: 'dsi' | 'rssi' | 'technique' | 'infra' | 'dirigeant';
  nom: string;
  prenom: string;
  email: string;
  telephone: string;
  contexte: string;
  /**
   * Renseignée automatiquement, utile pour répondre dans la bonne langue.
   */
  langue?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abonnes".
 */
export interface Abonne {
  id: number;
  email: string;
  /**
   * Langue de la page depuis laquelle l’inscription a été faite.
   */
  langue?: ('fr' | 'en') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'demandes';
        value: number | Demande;
      } | null)
    | ({
        relationTo: 'abonnes';
        value: number | Abonne;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  titre?: T;
  slug?: T;
  parent?: T;
  pole?: T;
  accrocheCourte?: T;
  surtitre?: T;
  accroche?: T;
  description?: T;
  image?: T;
  cta?:
    | T
    | {
        libelle?: T;
        chemin?: T;
      };
  sections?:
    | T
    | {
        bandePoles?:
          | T
          | {
              avecEnTete?: T;
              surtitre?: T;
              titreHaut?: T;
              titreBas?: T;
              id?: T;
              blockName?: T;
            };
        synergie?:
          | T
          | {
              surtitre?: T;
              titre?: T;
              texte?: T;
              id?: T;
              blockName?: T;
            };
        grille?:
          | T
          | {
              surtitre?: T;
              titre?: T;
              chapo?: T;
              intitules?:
                | T
                | {
                    texte?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        escalier?:
          | T
          | {
              surtitre?: T;
              titre?: T;
              chapo?: T;
              cartes?:
                | T
                | {
                    numero?: T;
                    picto?: T;
                    titre?: T;
                    texte?: T;
                    accentuee?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        enjeux?:
          | T
          | {
              surtitre?: T;
              titreHaut?: T;
              titreBas?: T;
              cartes?:
                | T
                | {
                    picto?: T;
                    titre?: T;
                    description?: T;
                    reponse?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        promesse?:
          | T
          | {
              surtitre?: T;
              titre?: T;
              id?: T;
              blockName?: T;
            };
        chiffres?:
          | T
          | {
              surtitre?: T;
              titre?: T;
              constat?: T;
              consequence?: T;
              statistiques?:
                | T
                | {
                    valeur?: T;
                    unite?: T;
                    libelle?: T;
                    precision?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        articles?:
          | T
          | {
              surtitre?: T;
              titre?: T;
              libelleAction?: T;
              nombre?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              surtitre?: T;
              titre?: T;
              image?: T;
              questions?:
                | T
                | {
                    question?: T;
                    reponse?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        differenciation?:
          | T
          | {
              surtitre?: T;
              titre?: T;
              habituelle?:
                | T
                | {
                    badge?: T;
                    titre?: T;
                    texte?: T;
                    puces?:
                      | T
                      | {
                          texte?: T;
                          id?: T;
                        };
                  };
              bone?:
                | T
                | {
                    badge?: T;
                    titre?: T;
                    texte?: T;
                    puces?:
                      | T
                      | {
                          texte?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        partenaires?:
          | T
          | {
              surtitre?: T;
              logos?:
                | T
                | {
                    fichier?: T;
                    nom?: T;
                    hauteur?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        posture?:
          | T
          | {
              surtitre?: T;
              refus?:
                | T
                | {
                    intitule?: T;
                    citation?: T;
                    precision?: T;
                  };
              engagement?:
                | T
                | {
                    intitule?: T;
                    citation?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pointsEntree?:
          | T
          | {
              surtitre?: T;
              titre?: T;
              enTetes?:
                | T
                | {
                    profil?: T;
                    pointEntree?: T;
                    livrable?: T;
                  };
              lignes?:
                | T
                | {
                    profil?: T;
                    pointEntree?: T;
                    livrable?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              surtitre?: T;
              titre?: T;
              chapo?: T;
              libelleChamp?: T;
              libelleBouton?: T;
              messageSucces?: T;
              id?: T;
              blockName?: T;
            };
        texteLong?:
          | T
          | {
              surtitre?: T;
              corps?: T;
              id?: T;
              blockName?: T;
            };
        reperes?:
          | T
          | {
              cartes?:
                | T
                | {
                    prefixe?: T;
                    valeur?: T;
                    suffixe?: T;
                    libelle?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        valeurs?:
          | T
          | {
              surtitre?: T;
              cartes?:
                | T
                | {
                    picto?: T;
                    titre?: T;
                    texte?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        archetype?:
          | T
          | {
              surtitre?: T;
              titre?: T;
              chapo?: T;
              traits?:
                | T
                | {
                    picto?: T;
                    libelle?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        equipe?:
          | T
          | {
              surtitre?: T;
              titre?: T;
              texte?: T;
              image?: T;
              statistiques?:
                | T
                | {
                    valeur?: T;
                    libelle?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        appelAction?:
          | T
          | {
              surtitre?: T;
              titre?: T;
              chapo?: T;
              cta?:
                | T
                | {
                    libelle?: T;
                    chemin?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  metaTitre?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  titre?: T;
  slug?: T;
  categorie?: T;
  publieLe?: T;
  minutesLecture?: T;
  extrait?: T;
  image?: T;
  contenu?: T;
  sections?:
    | T
    | {
        articles?:
          | T
          | {
              surtitre?: T;
              titre?: T;
              libelleAction?: T;
              nombre?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              surtitre?: T;
              titre?: T;
              image?: T;
              questions?:
                | T
                | {
                    question?: T;
                    reponse?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        appelAction?:
          | T
          | {
              surtitre?: T;
              titre?: T;
              chapo?: T;
              cta?:
                | T
                | {
                    libelle?: T;
                    chemin?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  metaTitre?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  _order?: T;
  nom?: T;
  libelleLong?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demandes_select".
 */
export interface DemandesSelect<T extends boolean = true> {
  profil?: T;
  nom?: T;
  prenom?: T;
  email?: T;
  telephone?: T;
  contexte?: T;
  langue?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abonnes_select".
 */
export interface AbonnesSelect<T extends boolean = true> {
  email?: T;
  langue?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accueil".
 */
export interface Accueil {
  id: number;
  /**
   * Ce que les moteurs et les réseaux sociaux affichent.
   */
  referencement: {
    /**
     * Une soixantaine de signes : au-delà, Google tronque.
     */
    metaTitre: string;
    /**
     * Cent cinquante à cent soixante signes.
     */
    metaDescription: string;
  };
  hero: {
    surtitre: string;
    /**
     * Chaque ligne se compose d’un verbe à pleine intensité et d’un complément atténué.
     */
    lignes?:
      | {
          verbe: string;
          complement: string;
          id?: string | null;
        }[]
      | null;
    chapo: string;
    cta: {
      libelle: string;
      chemin: string;
    };
    image?: (number | null) | Media;
  };
  enBref: {
    surtitre: string;
    titre: string;
    propos: string;
    /**
     * Affichée en retrait sous le propos.
     */
    precision: string;
    cta: {
      libelle: string;
      chemin: string;
    };
  };
  constat: {
    surtitre: string;
    titre: string;
    realite: {
      titre: string;
      /**
       * Affiché en très grand, en bleu de marque.
       */
      chiffre: string;
      legende: string;
      puces?:
        | {
            texte: string;
            id?: string | null;
          }[]
        | null;
      photo?: (number | null) | Media;
    };
    enjeu: {
      titre: string;
      texte: string;
      /**
       * Affichée en italique, guillemets compris.
       */
      citation: string;
      photo?: (number | null) | Media;
    };
  };
  promesse: {
    surtitre: string;
    titre: string;
  };
  role: {
    surtitre: string;
    titre: string;
    chapo: string;
    etapes?:
      | {
          numero: string;
          titre: string;
          texte: string;
          /**
           * Affiche la carte sur fond bleu.
           */
          accentuee?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Les deux colonnes se lisent par paires : la première entrée de gauche fait face à la première de droite.
   */
  positionnement: {
    surtitre: string;
    titre: string;
    gauche: {
      titre: string;
      sousTitre: string;
      entrees?:
        | {
            titre: string;
            texte: string;
            id?: string | null;
          }[]
        | null;
    };
    droite: {
      titre: string;
      sousTitre: string;
      entrees?:
        | {
            titre: string;
            texte: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  differenciation: {
    surtitre: string;
    titre: string;
    habituelle: {
      badge: string;
      titre: string;
      puces?:
        | {
            texte: string;
            id?: string | null;
          }[]
        | null;
    };
    bone: {
      badge: string;
      titre: string;
      puces?:
        | {
            texte: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  /**
   * Les trois bandes sont alimentées par les pages de pôle : leur accroche courte, leur surtitre et leur photo. Seuls les titres de la section se saisissent ici.
   */
  poles: {
    surtitre: string;
    /**
     * En grand, bleu de marque.
     */
    titreHaut: string;
    /**
     * Plus petite, marine.
     */
    titreBas: string;
  };
  chiffres: {
    surtitre: string;
    titre: string;
    /**
     * Première moitié du chapô, à pleine intensité.
     */
    constat: string;
    /**
     * Seconde moitié, affichée en retrait.
     */
    consequence: string;
    statistiques?:
      | {
          valeur: string;
          unite: string;
          libelle: string;
          precision: string;
          id?: string | null;
        }[]
      | null;
  };
  faq: {
    surtitre: string;
    titre: string;
    image?: (number | null) | Media;
    questions?:
      | {
          question: string;
          /**
           * Sans réponse, la question s’affiche sans pouvoir se déplier.
           */
          reponse?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  appel: {
    surtitre: string;
    titre: string;
    chapo: string;
    cta: {
      libelle: string;
      chemin: string;
    };
  };
  /**
   * Les fonds s’assombrissent dans l’ordre des profils : la progression suit la position, elle ne se saisit pas.
   */
  profils: {
    surtitre: string;
    /**
     * Affiché en retrait.
     */
    titreHaut: string;
    titreBas: string;
    liste?:
      | {
          picto: 'antenne' | 'securite' | 'balance' | 'boussole';
          titre: string;
          description: string;
          reponse: string;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  surtitreUne: string;
  libelleLire: string;
  /**
   * Lu par les lecteurs d’écran, pas affiché : la maquette ne titre pas la grille, mais neuf articles sans titre restent difficiles à situer.
   */
  titreListe: string;
  /**
   * Le filtre qui n’en applique aucun : « Tous les sujets ».
   */
  libelleTousSujets: string;
  /**
   * « {n} articles » — {n} est remplacé par le nombre trouvé.
   */
  gabaritCompte: string;
  libelleCharger: string;
  libelleSommaire: string;
  /**
   * Ajoutée au sommaire quand l’article porte une FAQ.
   */
  libelleFaq: string;
  libellePartageLinkedin: string;
  libelleCopierLien: string;
  libelleLienCopie: string;
  /**
   * Affiché quand un filtre ne ramène rien.
   */
  messageVide: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  /**
   * Ce que les moteurs et les réseaux sociaux affichent.
   */
  referencement: {
    /**
     * Une soixantaine de signes : au-delà, Google tronque.
     */
    metaTitre: string;
    /**
     * Cent cinquante à cent soixante signes.
     */
    metaDescription: string;
  };
  surtitre: string;
  titre: string;
  description: string;
  mentionChamps: string;
  /**
   * La valeur doit correspondre à l’un des rôles de la collection Demandes.
   */
  profils?:
    | {
        valeur: string;
        libelle: string;
        id?: string | null;
      }[]
    | null;
  libelles: {
    vousEtes: string;
    nom: string;
    prenom: string;
    email: string;
    telephone: string;
    contexte: string;
    contextePlaceholder: string;
    envoyer: string;
    mentionLegale: string;
    succes: string;
    erreur: string;
  };
  /**
   * Le plan est une vraie carte, dessinée par OpenStreetMap : ce sont ces coordonnées qui la centrent et qui posent le repère.
   */
  carte: {
    latitude: number;
    longitude: number;
    /**
     * 1 le monde, 19 la rue.
     */
    zoom: number;
    /**
     * Lu à la place de la carte, affiché au survol du repère, et recherché sur Google Maps.
     */
    intitule: string;
    /**
     * Posé sur la carte, et porté par l’adresse de l’encart.
     */
    libelleLien: string;
  };
  coordonnees: {
    badge: string;
    adresse: string;
    /**
     * Affichée à part du reste de la ligne : elle n’est pas écrite dans la page, mais rétablie à l’affichage, pour la dérober aux moissonneurs d’adresses.
     */
    email: string;
    /**
     * Ce qui suit l’adresse : téléphone, réseau social.
     */
    contact: string;
  };
  faq: {
    surtitre: string;
    titre: string;
    image?: (number | null) | Media;
    questions?:
      | {
          question: string;
          reponse?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  appel: {
    surtitre: string;
    titre: string;
    chapo: string;
    cta: {
      libelle: string;
      url: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  liensPrincipaux?:
    | {
        libelle: string;
        /**
         * Sans préfixe de langue : « /contact », pas « /fr/contact ».
         */
        chemin: string;
        avecDeroulant?: boolean | null;
        id?: string | null;
      }[]
    | null;
  boutonEntete: {
    libelle: string;
    /**
     * Sans préfixe de langue : « /contact », pas « /fr/contact ».
     */
    chemin: string;
  };
  poles?:
    | {
        titre: string;
        sousTitre: string;
        /**
         * Sans préfixe de langue : « /contact », pas « /fr/contact ».
         */
        chemin: string;
        id?: string | null;
      }[]
    | null;
  baseline: string;
  titrePoles: string;
  colonnes?:
    | {
        titre: string;
        liens?:
          | {
              libelle: string;
              /**
               * Sans préfixe de langue : « /contact », pas « /fr/contact ».
               */
              chemin: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  contact: {
    titre: string;
    libelleFormulaire: string;
    email: string;
    linkedin: string;
  };
  liensLegaux?:
    | {
        libelle: string;
        /**
         * Sans préfixe de langue : « /contact », pas « /fr/contact ».
         */
        chemin: string;
        id?: string | null;
      }[]
    | null;
  credit: {
    libelle: string;
    url: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accueil_select".
 */
export interface AccueilSelect<T extends boolean = true> {
  referencement?:
    | T
    | {
        metaTitre?: T;
        metaDescription?: T;
      };
  hero?:
    | T
    | {
        surtitre?: T;
        lignes?:
          | T
          | {
              verbe?: T;
              complement?: T;
              id?: T;
            };
        chapo?: T;
        cta?:
          | T
          | {
              libelle?: T;
              chemin?: T;
            };
        image?: T;
      };
  enBref?:
    | T
    | {
        surtitre?: T;
        titre?: T;
        propos?: T;
        precision?: T;
        cta?:
          | T
          | {
              libelle?: T;
              chemin?: T;
            };
      };
  constat?:
    | T
    | {
        surtitre?: T;
        titre?: T;
        realite?:
          | T
          | {
              titre?: T;
              chiffre?: T;
              legende?: T;
              puces?:
                | T
                | {
                    texte?: T;
                    id?: T;
                  };
              photo?: T;
            };
        enjeu?:
          | T
          | {
              titre?: T;
              texte?: T;
              citation?: T;
              photo?: T;
            };
      };
  promesse?:
    | T
    | {
        surtitre?: T;
        titre?: T;
      };
  role?:
    | T
    | {
        surtitre?: T;
        titre?: T;
        chapo?: T;
        etapes?:
          | T
          | {
              numero?: T;
              titre?: T;
              texte?: T;
              accentuee?: T;
              id?: T;
            };
      };
  positionnement?:
    | T
    | {
        surtitre?: T;
        titre?: T;
        gauche?:
          | T
          | {
              titre?: T;
              sousTitre?: T;
              entrees?:
                | T
                | {
                    titre?: T;
                    texte?: T;
                    id?: T;
                  };
            };
        droite?:
          | T
          | {
              titre?: T;
              sousTitre?: T;
              entrees?:
                | T
                | {
                    titre?: T;
                    texte?: T;
                    id?: T;
                  };
            };
      };
  differenciation?:
    | T
    | {
        surtitre?: T;
        titre?: T;
        habituelle?:
          | T
          | {
              badge?: T;
              titre?: T;
              puces?:
                | T
                | {
                    texte?: T;
                    id?: T;
                  };
            };
        bone?:
          | T
          | {
              badge?: T;
              titre?: T;
              puces?:
                | T
                | {
                    texte?: T;
                    id?: T;
                  };
            };
      };
  poles?:
    | T
    | {
        surtitre?: T;
        titreHaut?: T;
        titreBas?: T;
      };
  chiffres?:
    | T
    | {
        surtitre?: T;
        titre?: T;
        constat?: T;
        consequence?: T;
        statistiques?:
          | T
          | {
              valeur?: T;
              unite?: T;
              libelle?: T;
              precision?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        surtitre?: T;
        titre?: T;
        image?: T;
        questions?:
          | T
          | {
              question?: T;
              reponse?: T;
              id?: T;
            };
      };
  appel?:
    | T
    | {
        surtitre?: T;
        titre?: T;
        chapo?: T;
        cta?:
          | T
          | {
              libelle?: T;
              chemin?: T;
            };
      };
  profils?:
    | T
    | {
        surtitre?: T;
        titreHaut?: T;
        titreBas?: T;
        liste?:
          | T
          | {
              picto?: T;
              titre?: T;
              description?: T;
              reponse?: T;
              image?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  surtitreUne?: T;
  libelleLire?: T;
  titreListe?: T;
  libelleTousSujets?: T;
  gabaritCompte?: T;
  libelleCharger?: T;
  libelleSommaire?: T;
  libelleFaq?: T;
  libellePartageLinkedin?: T;
  libelleCopierLien?: T;
  libelleLienCopie?: T;
  messageVide?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  referencement?:
    | T
    | {
        metaTitre?: T;
        metaDescription?: T;
      };
  surtitre?: T;
  titre?: T;
  description?: T;
  mentionChamps?: T;
  profils?:
    | T
    | {
        valeur?: T;
        libelle?: T;
        id?: T;
      };
  libelles?:
    | T
    | {
        vousEtes?: T;
        nom?: T;
        prenom?: T;
        email?: T;
        telephone?: T;
        contexte?: T;
        contextePlaceholder?: T;
        envoyer?: T;
        mentionLegale?: T;
        succes?: T;
        erreur?: T;
      };
  carte?:
    | T
    | {
        latitude?: T;
        longitude?: T;
        zoom?: T;
        intitule?: T;
        libelleLien?: T;
      };
  coordonnees?:
    | T
    | {
        badge?: T;
        adresse?: T;
        email?: T;
        contact?: T;
      };
  faq?:
    | T
    | {
        surtitre?: T;
        titre?: T;
        image?: T;
        questions?:
          | T
          | {
              question?: T;
              reponse?: T;
              id?: T;
            };
      };
  appel?:
    | T
    | {
        surtitre?: T;
        titre?: T;
        chapo?: T;
        cta?:
          | T
          | {
              libelle?: T;
              url?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  liensPrincipaux?:
    | T
    | {
        libelle?: T;
        chemin?: T;
        avecDeroulant?: T;
        id?: T;
      };
  boutonEntete?:
    | T
    | {
        libelle?: T;
        chemin?: T;
      };
  poles?:
    | T
    | {
        titre?: T;
        sousTitre?: T;
        chemin?: T;
        id?: T;
      };
  baseline?: T;
  titrePoles?: T;
  colonnes?:
    | T
    | {
        titre?: T;
        liens?:
          | T
          | {
              libelle?: T;
              chemin?: T;
              id?: T;
            };
        id?: T;
      };
  contact?:
    | T
    | {
        titre?: T;
        libelleFormulaire?: T;
        email?: T;
        linkedin?: T;
      };
  liensLegaux?:
    | T
    | {
        libelle?: T;
        chemin?: T;
        id?: T;
      };
  credit?:
    | T
    | {
        libelle?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}